### ISSUE TITLE
Peer-to-peer code review 14-10-21

### ISSUE THREAD

**Issue by ghost** [AlexRS90/personalBrand-capstone1#1]
## HIGHLIGHTS
- Your design looks impressive
- Layout is done at top class
## SUGGESTIONS 
- It would be great if you could make the flex items of the Major section stretch vertically to make them appear online 
- You may consider making sure that about option in navigation gets its red colour when you actually visit the page

**Comment by micheaol** [comment]
Great work, great design Alex.

I observed that you styled your images with pixels.
Suggestion: It would be great if you can style images with % to make them responsive to the parent because styling images with pixels is like hard coding the image sizes to a fixed size.

Kindly check that.
Once again, good job Alex.

**Comment by AlexRS90** [comment]
Thanks for your comments guys I really appreciate them, so I will work on your suggestions to improve my project.
